@startuml

Settings : val blah: java.util.concurrent.atomic.AtomicInteger?
Done : val outputTest: String

[*] -> Settings

Settings --> UserSettings
Settings --> Logout
Settings --> Back

Settings --> NotLoggedIn
UserSettings --> Settings

Logout --> Settings

NotLoggedIn --> Login
NotLoggedIn --> Back

Login --> Settings

Settings -> Done

@enduml
